name       : python-sphinxcontrib-applehelp
version    : 1.0.1
release    : 1
source     :
    - https://github.com/sphinx-doc/sphinxcontrib-applehelp/archive/1.0.1.tar.gz : fa96dcb545e0391dd6a773408db69aefc31d0c8e900e60dfd7d4535c920f8acc
license    : BSD-2-Clause
component  : programming.python
summary    : Sphinx extension for Apple help books
description: |
    sphinxcontrib-applehelp is a sphinx extension which outputs Apple help books.
builddeps  :
    - pkgconfig(python3)
build      : |
    %python3_setup
install    : |
    %python3_install
