name       : python-sphinxcontrib-applehelp
version    : 1.0.2
release    : 2
source     :
    - https://github.com/sphinx-doc/sphinxcontrib-applehelp/archive/1.0.2.tar.gz : bc5223c931c8db3ebc501e91ed7cd13eaaf48b8fe69c4898a99ec355f4c89e01
license    : BSD-2-Clause
component  : programming.python
summary    : Sphinx extension for Apple help books
description: |
    sphinxcontrib-applehelp is a sphinx extension which outputs Apple help books.
builddeps  :
    - pkgconfig(python3)
build      : |
    %python3_setup
install    : |
    %python3_install
